FROM node:20.17-alpine3.20 AS builder

WORKDIR /usr/src/app

COPY package*.json ./
COPY nx.json ./
COPY tsconfig.base.json ./

RUN npm install

COPY . .

RUN npx nx reset && npx nx run-many -t build all

FROM nginx:alpine

COPY --from=builder /usr/src/app/dist/apps/client/ /usr/share/nginx/html


EXPOSE 80

ENV TZ=Europe/Madrid

CMD ["nginx", "-g", "daemon off;"]
