routes:
  - uri: /idp/*
    hosts:
      - dapaas.vera.kumori.cloud
      - cmc-forge.vera.kumori.cloud
    enable_websocket: true
    upstream:
      nodes:
        0.idp:80: 1
  - uri: /*
    host: dapaas.vera.kumori.cloud
    enable_websocket: true
    plugin_config_id: 1
    upstream:
      nodes:
        0.wui:80: 1
  - uri: /api/*
    host: dapaas.vera.kumori.cloud
    enable_websocket: true
    plugin_config_id: 1
    upstream:
      nodes:
        0.platform_api:80: 1

plugins:
  - name: openid-connect
  - name: serverless-post-function

plugin_configs:
  - id: 1
    desc: "Enable authentication plugin - DAPAAS"
    plugins:
      openid-connect:
        access_token_in_authorization_header: true
        client_id: superclientid
        client_secret: bar
        discovery: https://dapaas.vera.kumori.cloud/idp/.well-known/openid-configuration
        logout_path: /api/logout
        post_logout_redirect_uri: /
        redirect_uri: https://dapaas.vera.kumori.cloud/api/callback
        scope: openid email profile offline_access groups federated:id
        session:
          secret: Mysecretisasecretthatfewpeopleactuallyknownanythingabout
        set_access_token_header: true
        set_id_token_header: true
        set_refresh_token_header: true
        # unauth_action: deny # This should be used with APIs
        use_jwks: true

  - id: 2
    desc: "Enable authentication plugin - CMC"
    plugins:
      openid-connect:
        access_token_in_authorization_header: true
        client_id: superclientid
        client_secret: bar
        discovery: https://cmc-forge.vera.kumori.cloud/idp/.well-known/openid-configuration
        logout_path: /api/logout
        post_logout_redirect_uri: /
        redirect_uri: https://cmc-forge.vera.kumori.cloud/api/callback
        scope: openid email profile offline_access groups federated:id
        session:
          secret: Mysecretisasecretthatfewpeopleactuallyknownanythingabout
        set_access_token_header: true
        set_id_token_header: true
        set_refresh_token_header: true
        # unauth_action: deny # This should be used with APIs
        use_jwks: true
#END
